version: '3.9'
services: 
  mongodb:
    container_name: db-customers-transaction-query
    image: mongo
    hostname: host-bank
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: luis
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - data-mongodb:/var/lib/transactiondb
      - logs-mongodb:/var/log/transactiondb/
    networks:
      - bank

volumes:
  data-mongodb:
    name: data-bank
  logs-mongodb:
    name: logs-bank

networks:
  bank:
    name: bank